<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountryList extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = array(
  array('country_id' => '4','country_iso' => 'AF','country_iso3' => 'AFG','country_name' => 'Afghanistan','country_currency_code' => 'AFN','country_currency_name' => 'Afghani','country_status' => '0'),
  array('country_id' => '8','country_iso' => 'AL','country_iso3' => 'ALB','country_name' => 'Albania','country_currency_code' => 'ALL','country_currency_name' => 'Lek','country_status' => '0'),
  array('country_id' => '10','country_iso' => 'AQ','country_iso3' => 'ATA','country_name' => 'Antarctica','country_currency_code' => '','country_currency_name' => '','country_status' => '0'),
  array('country_id' => '12','country_iso' => 'DZ','country_iso3' => 'DZA','country_name' => 'Algeria','country_currency_code' => 'DZD','country_currency_name' => 'Dinar','country_status' => '0'),
  array('country_id' => '16','country_iso' => 'AS','country_iso3' => 'ASM','country_name' => 'American Samoa','country_currency_code' => 'USD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '20','country_iso' => 'AD','country_iso3' => 'AND','country_name' => 'Andorra','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '24','country_iso' => 'AO','country_iso3' => 'AGO','country_name' => 'Angola','country_currency_code' => 'AOA','country_currency_name' => 'Kwanza','country_status' => '0'),
  array('country_id' => '28','country_iso' => 'AG','country_iso3' => 'ATG','country_name' => 'Antigua and Barbuda','country_currency_code' => 'XCD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '31','country_iso' => 'AZ','country_iso3' => 'AZE','country_name' => 'Azerbaijan','country_currency_code' => 'AZN','country_currency_name' => 'Manat','country_status' => '0'),
  array('country_id' => '32','country_iso' => 'AR','country_iso3' => 'ARG','country_name' => 'Argentina','country_currency_code' => 'ARS','country_currency_name' => 'Peso','country_status' => '0'),
  array('country_id' => '36','country_iso' => 'AU','country_iso3' => 'AUS','country_name' => 'Australia','country_currency_code' => 'AUD','country_currency_name' => 'Dollar','country_status' => '1'),
  array('country_id' => '40','country_iso' => 'AT','country_iso3' => 'AUT','country_name' => 'Austria','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '44','country_iso' => 'BS','country_iso3' => 'BHS','country_name' => 'Bahamas','country_currency_code' => 'BSD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '48','country_iso' => 'BH','country_iso3' => 'BHR','country_name' => 'Bahrain','country_currency_code' => 'BHD','country_currency_name' => 'Dinar','country_status' => '0'),
  array('country_id' => '50','country_iso' => 'BD','country_iso3' => 'BGD','country_name' => 'Bangladesh','country_currency_code' => 'BDT','country_currency_name' => 'Taka','country_status' => '0'),
  array('country_id' => '51','country_iso' => 'AM','country_iso3' => 'ARM','country_name' => 'Armenia','country_currency_code' => 'AMD','country_currency_name' => 'Dram','country_status' => '0'),
  array('country_id' => '52','country_iso' => 'BB','country_iso3' => 'BRB','country_name' => 'Barbados','country_currency_code' => 'BBD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '56','country_iso' => 'BE','country_iso3' => 'BEL','country_name' => 'Belgium','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '60','country_iso' => 'BM','country_iso3' => 'BMU','country_name' => 'Bermuda','country_currency_code' => 'BMD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '64','country_iso' => 'BT','country_iso3' => 'BTN','country_name' => 'Bhutan','country_currency_code' => 'BTN','country_currency_name' => 'Ngultrum','country_status' => '0'),
  array('country_id' => '68','country_iso' => 'BO','country_iso3' => 'BOL','country_name' => 'Bolivia','country_currency_code' => 'BOB','country_currency_name' => 'Boliviano','country_status' => '0'),
  array('country_id' => '70','country_iso' => 'BA','country_iso3' => 'BIH','country_name' => 'Bosnia and Herzegovina','country_currency_code' => 'BAM','country_currency_name' => 'Marka','country_status' => '0'),
  array('country_id' => '72','country_iso' => 'BW','country_iso3' => 'BWA','country_name' => 'Botswana','country_currency_code' => 'BWP','country_currency_name' => 'Pula','country_status' => '0'),
  array('country_id' => '74','country_iso' => 'BV','country_iso3' => 'BVT','country_name' => 'Bouvet Island','country_currency_code' => 'NOK','country_currency_name' => 'Krone','country_status' => '0'),
  array('country_id' => '76','country_iso' => 'BR','country_iso3' => 'BRA','country_name' => 'Brazil','country_currency_code' => 'BRL','country_currency_name' => 'Real','country_status' => '0'),
  array('country_id' => '84','country_iso' => 'BZ','country_iso3' => 'BLZ','country_name' => 'Belize','country_currency_code' => 'BZD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '86','country_iso' => 'IO','country_iso3' => 'IOT','country_name' => 'British Indian Ocean Territory','country_currency_code' => 'USD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '90','country_iso' => 'SB','country_iso3' => 'SLB','country_name' => 'Solomon Islands','country_currency_code' => 'SBD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '92','country_iso' => 'VG','country_iso3' => 'VGB','country_name' => 'British Virgin Islands','country_currency_code' => 'USD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '96','country_iso' => 'BN','country_iso3' => 'BRN','country_name' => 'Brunei','country_currency_code' => 'BND','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '100','country_iso' => 'BG','country_iso3' => 'BGR','country_name' => 'Bulgaria','country_currency_code' => 'BGN','country_currency_name' => 'Lev','country_status' => '0'),
  array('country_id' => '104','country_iso' => 'MM','country_iso3' => 'MMR','country_name' => 'Myanmar','country_currency_code' => 'MMK','country_currency_name' => 'Kyat','country_status' => '0'),
  array('country_id' => '108','country_iso' => 'BI','country_iso3' => 'BDI','country_name' => 'Burundi','country_currency_code' => 'BIF','country_currency_name' => 'Franc','country_status' => '0'),
  array('country_id' => '112','country_iso' => 'BY','country_iso3' => 'BLR','country_name' => 'Belarus','country_currency_code' => 'BYR','country_currency_name' => 'Ruble','country_status' => '0'),
  array('country_id' => '116','country_iso' => 'KH','country_iso3' => 'KHM','country_name' => 'Cambodia','country_currency_code' => 'KHR','country_currency_name' => 'Riels','country_status' => '0'),
  array('country_id' => '120','country_iso' => 'CM','country_iso3' => 'CMR','country_name' => 'Cameroon','country_currency_code' => 'XAF','country_currency_name' => 'Franc','country_status' => '0'),
  array('country_id' => '124','country_iso' => 'CA','country_iso3' => 'CAN','country_name' => 'Canada','country_currency_code' => 'CAD','country_currency_name' => 'Dollar','country_status' => '1'),
  array('country_id' => '132','country_iso' => 'CV','country_iso3' => 'CPV','country_name' => 'Cape Verde','country_currency_code' => 'CVE','country_currency_name' => 'Escudo','country_status' => '0'),
  array('country_id' => '136','country_iso' => 'KY','country_iso3' => 'CYM','country_name' => 'Cayman Islands','country_currency_code' => 'KYD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '140','country_iso' => 'CF','country_iso3' => 'CAF','country_name' => 'Central African Republic','country_currency_code' => 'XAF','country_currency_name' => 'Franc','country_status' => '0'),
  array('country_id' => '144','country_iso' => 'LK','country_iso3' => 'LKA','country_name' => 'Sri Lanka','country_currency_code' => 'LKR','country_currency_name' => 'Rupee','country_status' => '0'),
  array('country_id' => '148','country_iso' => 'TD','country_iso3' => 'TCD','country_name' => 'Chad','country_currency_code' => 'XAF','country_currency_name' => 'Franc','country_status' => '0'),
  array('country_id' => '152','country_iso' => 'CL','country_iso3' => 'CHL','country_name' => 'Chile','country_currency_code' => 'CLP','country_currency_name' => 'Peso','country_status' => '0'),
  array('country_id' => '156','country_iso' => 'CN','country_iso3' => 'CHN','country_name' => 'China','country_currency_code' => 'CNY','country_currency_name' => 'Yuan Renminbi','country_status' => '0'),
  array('country_id' => '158','country_iso' => 'TW','country_iso3' => 'TWN','country_name' => 'Taiwan','country_currency_code' => 'TWD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '162','country_iso' => 'CX','country_iso3' => 'CXR','country_name' => 'Christmas Island','country_currency_code' => 'AUD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '166','country_iso' => 'CC','country_iso3' => 'CCK','country_name' => 'Cocos Islands','country_currency_code' => 'AUD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '170','country_iso' => 'CO','country_iso3' => 'COL','country_name' => 'Colombia','country_currency_code' => 'COP','country_currency_name' => 'Peso','country_status' => '0'),
  array('country_id' => '174','country_iso' => 'KM','country_iso3' => 'COM','country_name' => 'Comoros','country_currency_code' => 'KMF','country_currency_name' => 'Franc','country_status' => '0'),
  array('country_id' => '175','country_iso' => 'YT','country_iso3' => 'MYT','country_name' => 'Mayotte','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '178','country_iso' => 'CG','country_iso3' => 'COG','country_name' => 'Republic of the Congo','country_currency_code' => 'XAF','country_currency_name' => 'Franc','country_status' => '0'),
  array('country_id' => '180','country_iso' => 'CD','country_iso3' => 'COD','country_name' => 'Democratic Republic of the Congo','country_currency_code' => 'CDF','country_currency_name' => 'Franc','country_status' => '0'),
  array('country_id' => '184','country_iso' => 'CK','country_iso3' => 'COK','country_name' => 'Cook Islands','country_currency_code' => 'NZD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '188','country_iso' => 'CR','country_iso3' => 'CRI','country_name' => 'Costa Rica','country_currency_code' => 'CRC','country_currency_name' => 'Colon','country_status' => '0'),
  array('country_id' => '191','country_iso' => 'HR','country_iso3' => 'HRV','country_name' => 'Croatia','country_currency_code' => 'HRK','country_currency_name' => 'Kuna','country_status' => '0'),
  array('country_id' => '192','country_iso' => 'CU','country_iso3' => 'CUB','country_name' => 'Cuba','country_currency_code' => 'CUP','country_currency_name' => 'Peso','country_status' => '0'),
  array('country_id' => '196','country_iso' => 'CY','country_iso3' => 'CYP','country_name' => 'Cyprus','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '203','country_iso' => 'CZ','country_iso3' => 'CZE','country_name' => 'Czech Republic','country_currency_code' => 'CZK','country_currency_name' => 'Koruna','country_status' => '0'),
  array('country_id' => '204','country_iso' => 'BJ','country_iso3' => 'BEN','country_name' => 'Benin','country_currency_code' => 'XOF','country_currency_name' => 'Franc','country_status' => '0'),
  array('country_id' => '208','country_iso' => 'DK','country_iso3' => 'DNK','country_name' => 'Denmark','country_currency_code' => 'DKK','country_currency_name' => 'Krone','country_status' => '0'),
  array('country_id' => '212','country_iso' => 'DM','country_iso3' => 'DMA','country_name' => 'Dominica','country_currency_code' => 'XCD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '214','country_iso' => 'DO','country_iso3' => 'DOM','country_name' => 'Dominican Republic','country_currency_code' => 'DOP','country_currency_name' => 'Peso','country_status' => '0'),
  array('country_id' => '218','country_iso' => 'EC','country_iso3' => 'ECU','country_name' => 'Ecuador','country_currency_code' => 'USD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '222','country_iso' => 'SV','country_iso3' => 'SLV','country_name' => 'El Salvador','country_currency_code' => 'USD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '226','country_iso' => 'GQ','country_iso3' => 'GNQ','country_name' => 'Equatorial Guinea','country_currency_code' => 'XAF','country_currency_name' => 'Franc','country_status' => '0'),
  array('country_id' => '231','country_iso' => 'ET','country_iso3' => 'ETH','country_name' => 'Ethiopia','country_currency_code' => 'ETB','country_currency_name' => 'Birr','country_status' => '0'),
  array('country_id' => '232','country_iso' => 'ER','country_iso3' => 'ERI','country_name' => 'Eritrea','country_currency_code' => 'ERN','country_currency_name' => 'Nakfa','country_status' => '0'),
  array('country_id' => '233','country_iso' => 'EE','country_iso3' => 'EST','country_name' => 'Estonia','country_currency_code' => 'EEK','country_currency_name' => 'Kroon','country_status' => '0'),
  array('country_id' => '234','country_iso' => 'FO','country_iso3' => 'FRO','country_name' => 'Faroe Islands','country_currency_code' => 'DKK','country_currency_name' => 'Krone','country_status' => '0'),
  array('country_id' => '238','country_iso' => 'FK','country_iso3' => 'FLK','country_name' => 'Falkland Islands','country_currency_code' => 'FKP','country_currency_name' => 'Pound','country_status' => '0'),
  array('country_id' => '239','country_iso' => 'GS','country_iso3' => 'SGS','country_name' => 'South Georgia and the South Sandwich Islands','country_currency_code' => 'GBP','country_currency_name' => 'Pound','country_status' => '0'),
  array('country_id' => '242','country_iso' => 'FJ','country_iso3' => 'FJI','country_name' => 'Fiji','country_currency_code' => 'FJD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '246','country_iso' => 'FI','country_iso3' => 'FIN','country_name' => 'Finland','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '248','country_iso' => 'AX','country_iso3' => 'ALA','country_name' => 'Aland Islands','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '250','country_iso' => 'FR','country_iso3' => 'FRA','country_name' => 'France','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '254','country_iso' => 'GF','country_iso3' => 'GUF','country_name' => 'French Guiana','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '258','country_iso' => 'PF','country_iso3' => 'PYF','country_name' => 'French Polynesia','country_currency_code' => 'XPF','country_currency_name' => 'Franc','country_status' => '0'),
  array('country_id' => '260','country_iso' => 'TF','country_iso3' => 'ATF','country_name' => 'French Southern Territories','country_currency_code' => 'EUR','country_currency_name' => 'Euro  ','country_status' => '0'),
  array('country_id' => '262','country_iso' => 'DJ','country_iso3' => 'DJI','country_name' => 'Djibouti','country_currency_code' => 'DJF','country_currency_name' => 'Franc','country_status' => '0'),
  array('country_id' => '266','country_iso' => 'GA','country_iso3' => 'GAB','country_name' => 'Gabon','country_currency_code' => 'XAF','country_currency_name' => 'Franc','country_status' => '0'),
  array('country_id' => '268','country_iso' => 'GE','country_iso3' => 'GEO','country_name' => 'Georgia','country_currency_code' => 'GEL','country_currency_name' => 'Lari','country_status' => '0'),
  array('country_id' => '270','country_iso' => 'GM','country_iso3' => 'GMB','country_name' => 'Gambia','country_currency_code' => 'GMD','country_currency_name' => 'Dalasi','country_status' => '0'),
  array('country_id' => '275','country_iso' => 'PS','country_iso3' => 'PSE','country_name' => 'Palestinian Territory','country_currency_code' => 'ILS','country_currency_name' => 'Shekel','country_status' => '0'),
  array('country_id' => '276','country_iso' => 'DE','country_iso3' => 'DEU','country_name' => 'Germany','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '1'),
  array('country_id' => '288','country_iso' => 'GH','country_iso3' => 'GHA','country_name' => 'Ghana','country_currency_code' => 'GHS','country_currency_name' => 'Cedi','country_status' => '0'),
  array('country_id' => '292','country_iso' => 'GI','country_iso3' => 'GIB','country_name' => 'Gibraltar','country_currency_code' => 'GIP','country_currency_name' => 'Pound','country_status' => '0'),
  array('country_id' => '296','country_iso' => 'KI','country_iso3' => 'KIR','country_name' => 'Kiribati','country_currency_code' => 'AUD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '300','country_iso' => 'GR','country_iso3' => 'GRC','country_name' => 'Greece','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '304','country_iso' => 'GL','country_iso3' => 'GRL','country_name' => 'Greenland','country_currency_code' => 'DKK','country_currency_name' => 'Krone','country_status' => '0'),
  array('country_id' => '308','country_iso' => 'GD','country_iso3' => 'GRD','country_name' => 'Grenada','country_currency_code' => 'XCD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '312','country_iso' => 'GP','country_iso3' => 'GLP','country_name' => 'Guadeloupe','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '316','country_iso' => 'GU','country_iso3' => 'GUM','country_name' => 'Guam','country_currency_code' => 'USD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '320','country_iso' => 'GT','country_iso3' => 'GTM','country_name' => 'Guatemala','country_currency_code' => 'GTQ','country_currency_name' => 'Quetzal','country_status' => '0'),
  array('country_id' => '324','country_iso' => 'GN','country_iso3' => 'GIN','country_name' => 'Guinea','country_currency_code' => 'GNF','country_currency_name' => 'Franc','country_status' => '0'),
  array('country_id' => '328','country_iso' => 'GY','country_iso3' => 'GUY','country_name' => 'Guyana','country_currency_code' => 'GYD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '332','country_iso' => 'HT','country_iso3' => 'HTI','country_name' => 'Haiti','country_currency_code' => 'HTG','country_currency_name' => 'Gourde','country_status' => '0'),
  array('country_id' => '334','country_iso' => 'HM','country_iso3' => 'HMD','country_name' => 'Heard Island and McDonald Islands','country_currency_code' => 'AUD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '336','country_iso' => 'VA','country_iso3' => 'VAT','country_name' => 'Vatican','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '340','country_iso' => 'HN','country_iso3' => 'HND','country_name' => 'Honduras','country_currency_code' => 'HNL','country_currency_name' => 'Lempira','country_status' => '0'),
  array('country_id' => '344','country_iso' => 'HK','country_iso3' => 'HKG','country_name' => 'Hong Kong','country_currency_code' => 'HKD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '348','country_iso' => 'HU','country_iso3' => 'HUN','country_name' => 'Hungary','country_currency_code' => 'HUF','country_currency_name' => 'Forint','country_status' => '0'),
  array('country_id' => '352','country_iso' => 'IS','country_iso3' => 'ISL','country_name' => 'Iceland','country_currency_code' => 'ISK','country_currency_name' => 'Krona','country_status' => '0'),
  array('country_id' => '356','country_iso' => 'IN','country_iso3' => 'IND','country_name' => 'India','country_currency_code' => 'INR','country_currency_name' => 'Rupee','country_status' => '1'),
  array('country_id' => '360','country_iso' => 'ID','country_iso3' => 'IDN','country_name' => 'Indonesia','country_currency_code' => 'IDR','country_currency_name' => 'Rupiah','country_status' => '0'),
  array('country_id' => '364','country_iso' => 'IR','country_iso3' => 'IRN','country_name' => 'Iran','country_currency_code' => 'IRR','country_currency_name' => 'Rial','country_status' => '0'),
  array('country_id' => '368','country_iso' => 'IQ','country_iso3' => 'IRQ','country_name' => 'Iraq','country_currency_code' => 'IQD','country_currency_name' => 'Dinar','country_status' => '0'),
  array('country_id' => '372','country_iso' => 'IE','country_iso3' => 'IRL','country_name' => 'Ireland','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '376','country_iso' => 'IL','country_iso3' => 'ISR','country_name' => 'Israel','country_currency_code' => 'ILS','country_currency_name' => 'Shekel','country_status' => '0'),
  array('country_id' => '380','country_iso' => 'IT','country_iso3' => 'ITA','country_name' => 'Italy','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '384','country_iso' => 'CI','country_iso3' => 'CIV','country_name' => 'Ivory Coast','country_currency_code' => 'XOF','country_currency_name' => 'Franc','country_status' => '0'),
  array('country_id' => '388','country_iso' => 'JM','country_iso3' => 'JAM','country_name' => 'Jamaica','country_currency_code' => 'JMD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '392','country_iso' => 'JP','country_iso3' => 'JPN','country_name' => 'Japan','country_currency_code' => 'JPY','country_currency_name' => 'Yen','country_status' => '0'),
  array('country_id' => '398','country_iso' => 'KZ','country_iso3' => 'KAZ','country_name' => 'Kazakhstan','country_currency_code' => 'KZT','country_currency_name' => 'Tenge','country_status' => '0'),
  array('country_id' => '400','country_iso' => 'JO','country_iso3' => 'JOR','country_name' => 'Jordan','country_currency_code' => 'JOD','country_currency_name' => 'Dinar','country_status' => '0'),
  array('country_id' => '404','country_iso' => 'KE','country_iso3' => 'KEN','country_name' => 'Kenya','country_currency_code' => 'KES','country_currency_name' => 'Shilling','country_status' => '0'),
  array('country_id' => '408','country_iso' => 'KP','country_iso3' => 'PRK','country_name' => 'North Korea','country_currency_code' => 'KPW','country_currency_name' => 'Won','country_status' => '0'),
  array('country_id' => '410','country_iso' => 'KR','country_iso3' => 'KOR','country_name' => 'South Korea','country_currency_code' => 'KRW','country_currency_name' => 'Won','country_status' => '0'),
  array('country_id' => '414','country_iso' => 'KW','country_iso3' => 'KWT','country_name' => 'Kuwait','country_currency_code' => 'KWD','country_currency_name' => 'Dinar','country_status' => '0'),
  array('country_id' => '417','country_iso' => 'KG','country_iso3' => 'KGZ','country_name' => 'Kyrgyzstan','country_currency_code' => 'KGS','country_currency_name' => 'Som','country_status' => '0'),
  array('country_id' => '418','country_iso' => 'LA','country_iso3' => 'LAO','country_name' => 'Laos','country_currency_code' => 'LAK','country_currency_name' => 'Kip','country_status' => '0'),
  array('country_id' => '422','country_iso' => 'LB','country_iso3' => 'LBN','country_name' => 'Lebanon','country_currency_code' => 'LBP','country_currency_name' => 'Pound','country_status' => '0'),
  array('country_id' => '426','country_iso' => 'LS','country_iso3' => 'LSO','country_name' => 'Lesotho','country_currency_code' => 'LSL','country_currency_name' => 'Loti','country_status' => '0'),
  array('country_id' => '428','country_iso' => 'LV','country_iso3' => 'LVA','country_name' => 'Latvia','country_currency_code' => 'LVL','country_currency_name' => 'Lat','country_status' => '0'),
  array('country_id' => '430','country_iso' => 'LR','country_iso3' => 'LBR','country_name' => 'Liberia','country_currency_code' => 'LRD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '434','country_iso' => 'LY','country_iso3' => 'LBY','country_name' => 'Libya','country_currency_code' => 'LYD','country_currency_name' => 'Dinar','country_status' => '0'),
  array('country_id' => '438','country_iso' => 'LI','country_iso3' => 'LIE','country_name' => 'Liechtenstein','country_currency_code' => 'CHF','country_currency_name' => 'Franc','country_status' => '0'),
  array('country_id' => '440','country_iso' => 'LT','country_iso3' => 'LTU','country_name' => 'Lithuania','country_currency_code' => 'LTL','country_currency_name' => 'Litas','country_status' => '0'),
  array('country_id' => '442','country_iso' => 'LU','country_iso3' => 'LUX','country_name' => 'Luxembourg','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '446','country_iso' => 'MO','country_iso3' => 'MAC','country_name' => 'Macao','country_currency_code' => 'MOP','country_currency_name' => 'Pataca','country_status' => '0'),
  array('country_id' => '450','country_iso' => 'MG','country_iso3' => 'MDG','country_name' => 'Madagascar','country_currency_code' => 'MGA','country_currency_name' => 'Ariary','country_status' => '0'),
  array('country_id' => '454','country_iso' => 'MW','country_iso3' => 'MWI','country_name' => 'Malawi','country_currency_code' => 'MWK','country_currency_name' => 'Kwacha','country_status' => '0'),
  array('country_id' => '458','country_iso' => 'MY','country_iso3' => 'MYS','country_name' => 'Malaysia','country_currency_code' => 'MYR','country_currency_name' => 'Ringgit','country_status' => '0'),
  array('country_id' => '462','country_iso' => 'MV','country_iso3' => 'MDV','country_name' => 'Maldives','country_currency_code' => 'MVR','country_currency_name' => 'Rufiyaa','country_status' => '0'),
  array('country_id' => '466','country_iso' => 'ML','country_iso3' => 'MLI','country_name' => 'Mali','country_currency_code' => 'XOF','country_currency_name' => 'Franc','country_status' => '0'),
  array('country_id' => '470','country_iso' => 'MT','country_iso3' => 'MLT','country_name' => 'Malta','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '474','country_iso' => 'MQ','country_iso3' => 'MTQ','country_name' => 'Martinique','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '478','country_iso' => 'MR','country_iso3' => 'MRT','country_name' => 'Mauritania','country_currency_code' => 'MRO','country_currency_name' => 'Ouguiya','country_status' => '0'),
  array('country_id' => '480','country_iso' => 'MU','country_iso3' => 'MUS','country_name' => 'Mauritius','country_currency_code' => 'MUR','country_currency_name' => 'Rupee','country_status' => '0'),
  array('country_id' => '484','country_iso' => 'MX','country_iso3' => 'MEX','country_name' => 'Mexico','country_currency_code' => 'MXN','country_currency_name' => 'Peso','country_status' => '0'),
  array('country_id' => '492','country_iso' => 'MC','country_iso3' => 'MCO','country_name' => 'Monaco','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '496','country_iso' => 'MN','country_iso3' => 'MNG','country_name' => 'Mongolia','country_currency_code' => 'MNT','country_currency_name' => 'Tugrik','country_status' => '0'),
  array('country_id' => '498','country_iso' => 'MD','country_iso3' => 'MDA','country_name' => 'Moldova','country_currency_code' => 'MDL','country_currency_name' => 'Leu','country_status' => '0'),
  array('country_id' => '499','country_iso' => 'ME','country_iso3' => 'MNE','country_name' => 'Montenegro','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '500','country_iso' => 'MS','country_iso3' => 'MSR','country_name' => 'Montserrat','country_currency_code' => 'XCD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '504','country_iso' => 'MA','country_iso3' => 'MAR','country_name' => 'Morocco','country_currency_code' => 'MAD','country_currency_name' => 'Dirham','country_status' => '0'),
  array('country_id' => '508','country_iso' => 'MZ','country_iso3' => 'MOZ','country_name' => 'Mozambique','country_currency_code' => 'MZN','country_currency_name' => 'Meticail','country_status' => '0'),
  array('country_id' => '512','country_iso' => 'OM','country_iso3' => 'OMN','country_name' => 'Oman','country_currency_code' => 'OMR','country_currency_name' => 'Rial','country_status' => '0'),
  array('country_id' => '516','country_iso' => 'NA','country_iso3' => 'NAM','country_name' => 'Namibia','country_currency_code' => 'NAD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '520','country_iso' => 'NR','country_iso3' => 'NRU','country_name' => 'Nauru','country_currency_code' => 'AUD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '524','country_iso' => 'NP','country_iso3' => 'NPL','country_name' => 'Nepal','country_currency_code' => 'NPR','country_currency_name' => 'Rupee','country_status' => '0'),
  array('country_id' => '528','country_iso' => 'NL','country_iso3' => 'NLD','country_name' => 'Netherlands','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '530','country_iso' => 'AN','country_iso3' => 'ANT','country_name' => 'Netherlands Antilles','country_currency_code' => 'ANG','country_currency_name' => 'Guilder','country_status' => '0'),
  array('country_id' => '533','country_iso' => 'AW','country_iso3' => 'ABW','country_name' => 'Aruba','country_currency_code' => 'AWG','country_currency_name' => 'Guilder','country_status' => '0'),
  array('country_id' => '540','country_iso' => 'NC','country_iso3' => 'NCL','country_name' => 'New Caledonia','country_currency_code' => 'XPF','country_currency_name' => 'Franc','country_status' => '0'),
  array('country_id' => '548','country_iso' => 'VU','country_iso3' => 'VUT','country_name' => 'Vanuatu','country_currency_code' => 'VUV','country_currency_name' => 'Vatu','country_status' => '0'),
  array('country_id' => '554','country_iso' => 'NZ','country_iso3' => 'NZL','country_name' => 'New Zealand','country_currency_code' => 'NZD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '558','country_iso' => 'NI','country_iso3' => 'NIC','country_name' => 'Nicaragua','country_currency_code' => 'NIO','country_currency_name' => 'Cordoba','country_status' => '0'),
  array('country_id' => '562','country_iso' => 'NE','country_iso3' => 'NER','country_name' => 'Niger','country_currency_code' => 'XOF','country_currency_name' => 'Franc','country_status' => '0'),
  array('country_id' => '566','country_iso' => 'NG','country_iso3' => 'NGA','country_name' => 'Nigeria','country_currency_code' => 'NGN','country_currency_name' => 'Naira','country_status' => '0'),
  array('country_id' => '570','country_iso' => 'NU','country_iso3' => 'NIU','country_name' => 'Niue','country_currency_code' => 'NZD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '574','country_iso' => 'NF','country_iso3' => 'NFK','country_name' => 'Norfolk Island','country_currency_code' => 'AUD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '578','country_iso' => 'NO','country_iso3' => 'NOR','country_name' => 'Norway','country_currency_code' => 'NOK','country_currency_name' => 'Krone','country_status' => '0'),
  array('country_id' => '580','country_iso' => 'MP','country_iso3' => 'MNP','country_name' => 'Northern Mariana Islands','country_currency_code' => 'USD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '581','country_iso' => 'UM','country_iso3' => 'UMI','country_name' => 'United States Minor Outlying Islands','country_currency_code' => 'USD','country_currency_name' => 'Dollar ','country_status' => '0'),
  array('country_id' => '583','country_iso' => 'FM','country_iso3' => 'FSM','country_name' => 'Micronesia','country_currency_code' => 'USD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '584','country_iso' => 'MH','country_iso3' => 'MHL','country_name' => 'Marshall Islands','country_currency_code' => 'USD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '585','country_iso' => 'PW','country_iso3' => 'PLW','country_name' => 'Palau','country_currency_code' => 'USD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '586','country_iso' => 'PK','country_iso3' => 'PAK','country_name' => 'Pakistan','country_currency_code' => 'PKR','country_currency_name' => 'Rupee','country_status' => '0'),
  array('country_id' => '591','country_iso' => 'PA','country_iso3' => 'PAN','country_name' => 'Panama','country_currency_code' => 'PAB','country_currency_name' => 'Balboa','country_status' => '0'),
  array('country_id' => '598','country_iso' => 'PG','country_iso3' => 'PNG','country_name' => 'Papua New Guinea','country_currency_code' => 'PGK','country_currency_name' => 'Kina','country_status' => '0'),
  array('country_id' => '600','country_iso' => 'PY','country_iso3' => 'PRY','country_name' => 'Paraguay','country_currency_code' => 'PYG','country_currency_name' => 'Guarani','country_status' => '0'),
  array('country_id' => '604','country_iso' => 'PE','country_iso3' => 'PER','country_name' => 'Peru','country_currency_code' => 'PEN','country_currency_name' => 'Sol','country_status' => '0'),
  array('country_id' => '608','country_iso' => 'PH','country_iso3' => 'PHL','country_name' => 'Philippines','country_currency_code' => 'PHP','country_currency_name' => 'Peso','country_status' => '0'),
  array('country_id' => '612','country_iso' => 'PN','country_iso3' => 'PCN','country_name' => 'Pitcairn','country_currency_code' => 'NZD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '616','country_iso' => 'PL','country_iso3' => 'POL','country_name' => 'Poland','country_currency_code' => 'PLN','country_currency_name' => 'Zloty','country_status' => '0'),
  array('country_id' => '620','country_iso' => 'PT','country_iso3' => 'PRT','country_name' => 'Portugal','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '624','country_iso' => 'GW','country_iso3' => 'GNB','country_name' => 'Guinea-Bissau','country_currency_code' => 'XOF','country_currency_name' => 'Franc','country_status' => '0'),
  array('country_id' => '626','country_iso' => 'TL','country_iso3' => 'TLS','country_name' => 'East Timor','country_currency_code' => 'USD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '630','country_iso' => 'PR','country_iso3' => 'PRI','country_name' => 'Puerto Rico','country_currency_code' => 'USD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '634','country_iso' => 'QA','country_iso3' => 'QAT','country_name' => 'Qatar','country_currency_code' => 'QAR','country_currency_name' => 'Rial','country_status' => '0'),
  array('country_id' => '638','country_iso' => 'RE','country_iso3' => 'REU','country_name' => 'Reunion','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '642','country_iso' => 'RO','country_iso3' => 'ROU','country_name' => 'Romania','country_currency_code' => 'RON','country_currency_name' => 'Leu','country_status' => '0'),
  array('country_id' => '643','country_iso' => 'RU','country_iso3' => 'RUS','country_name' => 'Russia','country_currency_code' => 'RUB','country_currency_name' => 'Ruble','country_status' => '0'),
  array('country_id' => '646','country_iso' => 'RW','country_iso3' => 'RWA','country_name' => 'Rwanda','country_currency_code' => 'RWF','country_currency_name' => 'Franc','country_status' => '0'),
  array('country_id' => '652','country_iso' => 'BL','country_iso3' => 'BLM','country_name' => 'Saint Barthelemy','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '654','country_iso' => 'SH','country_iso3' => 'SHN','country_name' => 'Saint Helena','country_currency_code' => 'SHP','country_currency_name' => 'Pound','country_status' => '0'),
  array('country_id' => '659','country_iso' => 'KN','country_iso3' => 'KNA','country_name' => 'Saint Kitts and Nevis','country_currency_code' => 'XCD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '660','country_iso' => 'AI','country_iso3' => 'AIA','country_name' => 'Anguilla','country_currency_code' => 'XCD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '662','country_iso' => 'LC','country_iso3' => 'LCA','country_name' => 'Saint Lucia','country_currency_code' => 'XCD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '663','country_iso' => 'MF','country_iso3' => 'MAF','country_name' => 'Saint Martin','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '666','country_iso' => 'PM','country_iso3' => 'SPM','country_name' => 'Saint Pierre and Miquelon','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '670','country_iso' => 'VC','country_iso3' => 'VCT','country_name' => 'Saint Vincent and the Grenadines','country_currency_code' => 'XCD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '674','country_iso' => 'SM','country_iso3' => 'SMR','country_name' => 'San Marino','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '678','country_iso' => 'ST','country_iso3' => 'STP','country_name' => 'Sao Tome and Principe','country_currency_code' => 'STD','country_currency_name' => 'Dobra','country_status' => '0'),
  array('country_id' => '682','country_iso' => 'SA','country_iso3' => 'SAU','country_name' => 'Saudi Arabia','country_currency_code' => 'SAR','country_currency_name' => 'Rial','country_status' => '0'),
  array('country_id' => '686','country_iso' => 'SN','country_iso3' => 'SEN','country_name' => 'Senegal','country_currency_code' => 'XOF','country_currency_name' => 'Franc','country_status' => '0'),
  array('country_id' => '688','country_iso' => 'RS','country_iso3' => 'SRB','country_name' => 'Serbia','country_currency_code' => 'RSD','country_currency_name' => 'Dinar','country_status' => '0'),
  array('country_id' => '690','country_iso' => 'SC','country_iso3' => 'SYC','country_name' => 'Seychelles','country_currency_code' => 'SCR','country_currency_name' => 'Rupee','country_status' => '0'),
  array('country_id' => '694','country_iso' => 'SL','country_iso3' => 'SLE','country_name' => 'Sierra Leone','country_currency_code' => 'SLL','country_currency_name' => 'Leone','country_status' => '0'),
  array('country_id' => '702','country_iso' => 'SG','country_iso3' => 'SGP','country_name' => 'Singapore','country_currency_code' => 'SGD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '703','country_iso' => 'SK','country_iso3' => 'SVK','country_name' => 'Slovakia','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '704','country_iso' => 'VN','country_iso3' => 'VNM','country_name' => 'Vietnam','country_currency_code' => 'VND','country_currency_name' => 'Dong','country_status' => '0'),
  array('country_id' => '705','country_iso' => 'SI','country_iso3' => 'SVN','country_name' => 'Slovenia','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '706','country_iso' => 'SO','country_iso3' => 'SOM','country_name' => 'Somalia','country_currency_code' => 'SOS','country_currency_name' => 'Shilling','country_status' => '0'),
  array('country_id' => '710','country_iso' => 'ZA','country_iso3' => 'ZAF','country_name' => 'South Africa','country_currency_code' => 'ZAR','country_currency_name' => 'Rand','country_status' => '0'),
  array('country_id' => '716','country_iso' => 'ZW','country_iso3' => 'ZWE','country_name' => 'Zimbabwe','country_currency_code' => 'ZWL','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '724','country_iso' => 'ES','country_iso3' => 'ESP','country_name' => 'Spain','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '732','country_iso' => 'EH','country_iso3' => 'ESH','country_name' => 'Western Sahara','country_currency_code' => 'MAD','country_currency_name' => 'Dirham','country_status' => '0'),
  array('country_id' => '736','country_iso' => 'SD','country_iso3' => 'SDN','country_name' => 'Sudan','country_currency_code' => 'SDG','country_currency_name' => 'Dinar','country_status' => '0'),
  array('country_id' => '740','country_iso' => 'SR','country_iso3' => 'SUR','country_name' => 'Suriname','country_currency_code' => 'SRD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '744','country_iso' => 'SJ','country_iso3' => 'SJM','country_name' => 'Svalbard and Jan Mayen','country_currency_code' => 'NOK','country_currency_name' => 'Krone','country_status' => '0'),
  array('country_id' => '748','country_iso' => 'SZ','country_iso3' => 'SWZ','country_name' => 'Swaziland','country_currency_code' => 'SZL','country_currency_name' => 'Lilangeni','country_status' => '0'),
  array('country_id' => '752','country_iso' => 'SE','country_iso3' => 'SWE','country_name' => 'Sweden','country_currency_code' => 'SEK','country_currency_name' => 'Krona','country_status' => '0'),
  array('country_id' => '756','country_iso' => 'CH','country_iso3' => 'CHE','country_name' => 'Switzerland','country_currency_code' => 'CHF','country_currency_name' => 'Franc','country_status' => '0'),
  array('country_id' => '760','country_iso' => 'SY','country_iso3' => 'SYR','country_name' => 'Syria','country_currency_code' => 'SYP','country_currency_name' => 'Pound','country_status' => '0'),
  array('country_id' => '762','country_iso' => 'TJ','country_iso3' => 'TJK','country_name' => 'Tajikistan','country_currency_code' => 'TJS','country_currency_name' => 'Somoni','country_status' => '0'),
  array('country_id' => '764','country_iso' => 'TH','country_iso3' => 'THA','country_name' => 'Thailand','country_currency_code' => 'THB','country_currency_name' => 'Baht','country_status' => '0'),
  array('country_id' => '768','country_iso' => 'TG','country_iso3' => 'TGO','country_name' => 'Togo','country_currency_code' => 'XOF','country_currency_name' => 'Franc','country_status' => '0'),
  array('country_id' => '772','country_iso' => 'TK','country_iso3' => 'TKL','country_name' => 'Tokelau','country_currency_code' => 'NZD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '776','country_iso' => 'TO','country_iso3' => 'TON','country_name' => 'Tonga','country_currency_code' => 'TOP','country_currency_name' => 'Pa\'anga','country_status' => '0'),
  array('country_id' => '780','country_iso' => 'TT','country_iso3' => 'TTO','country_name' => 'Trinidad and Tobago','country_currency_code' => 'TTD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '784','country_iso' => 'AE','country_iso3' => 'ARE','country_name' => 'United Arab Emirates','country_currency_code' => 'AED','country_currency_name' => 'Dirham','country_status' => '0'),
  array('country_id' => '788','country_iso' => 'TN','country_iso3' => 'TUN','country_name' => 'Tunisia','country_currency_code' => 'TND','country_currency_name' => 'Dinar','country_status' => '0'),
  array('country_id' => '792','country_iso' => 'TR','country_iso3' => 'TUR','country_name' => 'Turkey','country_currency_code' => 'TRY','country_currency_name' => 'Lira','country_status' => '0'),
  array('country_id' => '795','country_iso' => 'TM','country_iso3' => 'TKM','country_name' => 'Turkmenistan','country_currency_code' => 'TMT','country_currency_name' => 'Manat','country_status' => '0'),
  array('country_id' => '796','country_iso' => 'TC','country_iso3' => 'TCA','country_name' => 'Turks and Caicos Islands','country_currency_code' => 'USD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '798','country_iso' => 'TV','country_iso3' => 'TUV','country_name' => 'Tuvalu','country_currency_code' => 'AUD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '800','country_iso' => 'UG','country_iso3' => 'UGA','country_name' => 'Uganda','country_currency_code' => 'UGX','country_currency_name' => 'Shilling','country_status' => '0'),
  array('country_id' => '804','country_iso' => 'UA','country_iso3' => 'UKR','country_name' => 'Ukraine','country_currency_code' => 'UAH','country_currency_name' => 'Hryvnia','country_status' => '0'),
  array('country_id' => '807','country_iso' => 'MK','country_iso3' => 'MKD','country_name' => 'Macedonia','country_currency_code' => 'MKD','country_currency_name' => 'Denar','country_status' => '0'),
  array('country_id' => '818','country_iso' => 'EG','country_iso3' => 'EGY','country_name' => 'Egypt','country_currency_code' => 'EGP','country_currency_name' => 'Pound','country_status' => '0'),
  array('country_id' => '826','country_iso' => 'GB','country_iso3' => 'GBR','country_name' => 'United Kingdom','country_currency_code' => 'GBP','country_currency_name' => 'Pound','country_status' => '1'),
  array('country_id' => '831','country_iso' => 'GG','country_iso3' => 'GGY','country_name' => 'Guernsey','country_currency_code' => 'GBP','country_currency_name' => 'Pound','country_status' => '0'),
  array('country_id' => '832','country_iso' => 'JE','country_iso3' => 'JEY','country_name' => 'Jersey','country_currency_code' => 'GBP','country_currency_name' => 'Pound','country_status' => '0'),
  array('country_id' => '833','country_iso' => 'IM','country_iso3' => 'IMN','country_name' => 'Isle of Man','country_currency_code' => 'GBP','country_currency_name' => 'Pound','country_status' => '0'),
  array('country_id' => '834','country_iso' => 'TZ','country_iso3' => 'TZA','country_name' => 'Tanzania','country_currency_code' => 'TZS','country_currency_name' => 'Shilling','country_status' => '0'),
  array('country_id' => '840','country_iso' => 'US','country_iso3' => 'USA','country_name' => 'United States','country_currency_code' => 'USD','country_currency_name' => 'Dollar','country_status' => '1'),
  array('country_id' => '850','country_iso' => 'VI','country_iso3' => 'VIR','country_name' => 'U.S. Virgin Islands','country_currency_code' => 'USD','country_currency_name' => 'Dollar','country_status' => '0'),
  array('country_id' => '854','country_iso' => 'BF','country_iso3' => 'BFA','country_name' => 'Burkina Faso','country_currency_code' => 'XOF','country_currency_name' => 'Franc','country_status' => '0'),
  array('country_id' => '855','country_iso' => 'XK','country_iso3' => 'XKX','country_name' => 'Kosovo','country_currency_code' => 'EUR','country_currency_name' => 'Euro','country_status' => '0'),
  array('country_id' => '858','country_iso' => 'UY','country_iso3' => 'URY','country_name' => 'Uruguay','country_currency_code' => 'UYU','country_currency_name' => 'Peso','country_status' => '0'),
  array('country_id' => '860','country_iso' => 'UZ','country_iso3' => 'UZB','country_name' => 'Uzbekistan','country_currency_code' => 'UZS','country_currency_name' => 'Som','country_status' => '0'),
  array('country_id' => '862','country_iso' => 'VE','country_iso3' => 'VEN','country_name' => 'Venezuela','country_currency_code' => 'VEF','country_currency_name' => 'Bolivar','country_status' => '0'),
  array('country_id' => '876','country_iso' => 'WF','country_iso3' => 'WLF','country_name' => 'Wallis and Futuna','country_currency_code' => 'XPF','country_currency_name' => 'Franc','country_status' => '0'),
  array('country_id' => '882','country_iso' => 'WS','country_iso3' => 'WSM','country_name' => 'Samoa','country_currency_code' => 'WST','country_currency_name' => 'Tala','country_status' => '0'),
  array('country_id' => '887','country_iso' => 'YE','country_iso3' => 'YEM','country_name' => 'Yemen','country_currency_code' => 'YER','country_currency_name' => 'Rial','country_status' => '0'),
  array('country_id' => '891','country_iso' => 'CS','country_iso3' => 'SCG','country_name' => 'Serbia and Montenegro','country_currency_code' => 'RSD','country_currency_name' => 'Dinar','country_status' => '0'),
  array('country_id' => '894','country_iso' => 'ZM','country_iso3' => 'ZMB','country_name' => 'Zambia','country_currency_code' => 'ZMK','country_currency_name' => 'Kwacha','country_status' => '0'),
  array('country_id' => '895','country_iso' => 'GB-ENG','country_iso3' => 'GB-ENG','country_name' => 'England','country_currency_code' => 'GBP','country_currency_name' => 'Pound sterling','country_status' => '0'),
  array('country_id' => '896','country_iso' => 'GB-NIR','country_iso3' => 'GB-NIR','country_name' => 'Northern Ireland','country_currency_code' => 'GBP','country_currency_name' => 'Pound sterling','country_status' => '0'),
  array('country_id' => '897','country_iso' => 'GB-SCT','country_iso3' => 'GB-SCT','country_name' => 'Scotland','country_currency_code' => 'GBP','country_currency_name' => 'Pound sterling','country_status' => '0'),
  array('country_id' => '898','country_iso' => 'GB-WLS','country_iso3' => 'GB-WLS','country_name' => 'Wales','country_currency_code' => 'GBP','country_currency_name' => 'Pound sterling','country_status' => '0')
);
        foreach ($countries as $key => $list) {  
            DB::table('countries')->insert($list);
        }      

    }
}
